### ISSUE TITLE
Does not work with CoffeeScript 1.7 when Jamesfile in CoffeeScript

### ISSUE THREAD

**Issue by vesse** [leonidas/james.js#19]
CoffeeScript 1.7.0 requires the compiler to be [explicitly registered before requiring CoffeeScript files](http://coffeescript.org/#changelog) in Node, ie. `require('coffee-script/register');`. Currently James will fail with

```
Error: Cannot find module '/home/vesse/github/invoices-server/Jamesfile'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vesse/github/invoices-server/node_modules/james/lib/runner.js:5:17)
```

Could e.g. add the `require` call inside a try-catch in `runner.js`, or maybe parse the `VERSION` attribute of required CoffeeScript module.
